spring:
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      schema-locations: classpath:schema-h2.sql
      platform: h2
      mode: always

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jwt:
    header: Authorization
    secret: eWhtOTIwN2FzamZpYXNqZGZpc2FqZGYxMjMxMjMxMjMK
    access-token-validity-in-seconds: 600